[tool.poetry]
name = "ci"
version = "0.1.0"
description = ""
authors = ["Yankı Sırtaş <yankisirtas@hotmail.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
Pillow = "^9.4.0"
rumps = "^0.4.0"
pyinstaller = "^5.7.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
